#!/usr/bin/env python3
"""
Antigravity Quota & Token Monitor - Lightweight Token Collector
Extracts exact token metrics directly from Antigravity's internal SQLite databases.
"""

import os
import sys
import glob
import json
import sqlite3
import struct
import urllib.parse
from pathlib import Path
from datetime import datetime
from collections import defaultdict
from contextlib import closing

GEMINI_HOME = os.path.join(os.path.expanduser("~"), ".gemini")

DATA_SOURCES = [
    os.path.join(GEMINI_HOME, "antigravity-ide", "conversations"),
    os.path.join(GEMINI_HOME, "antigravity", "conversations"),
    os.path.join(GEMINI_HOME, "antigravity-cli", "conversations"),
]

def parse_proto(data):
    """Fast protobuf wire format parser"""
    pos = 0
    fields = {}
    length_data = len(data)
    while pos < length_data:
        try:
            key = 0
            shift = 0
            while True:
                if pos >= length_data or shift > 64:
                    return fields
                b = data[pos]
                pos += 1
                key |= (b & 0x7F) << shift
                shift += 7
                if not (b & 0x80):
                    break
            field_num = key >> 3
            wire_type = key & 0x7
            if wire_type == 0:  # Varint
                val = 0
                shift = 0
                while True:
                    if pos >= length_data or shift > 64:
                        return fields
                    b = data[pos]
                    pos += 1
                    val |= (b & 0x7F) << shift
                    shift += 7
                    if not (b & 0x80):
                        break
                fields.setdefault(field_num, []).append(('varint', val))
            elif wire_type == 1:  # fixed64
                if pos + 8 > length_data:
                    break
                val = struct.unpack('<Q', data[pos:pos+8])[0]
                pos += 8
                fields.setdefault(field_num, []).append(('fixed64', val))
            elif wire_type == 2:  # bytes / sub-message
                length = 0
                shift = 0
                while True:
                    if pos >= length_data or shift > 64:
                        return fields
                    b = data[pos]
                    pos += 1
                    length |= (b & 0x7F) << shift
                    shift += 7
                    if not (b & 0x80):
                        break
                if length < 0 or pos + length > length_data:
                    break
                payload = data[pos:pos+length]
                pos += length
                fields.setdefault(field_num, []).append(('bytes', payload))
            elif wire_type == 5:  # fixed32
                if pos + 4 > length_data:
                    break
                val = struct.unpack('<I', data[pos:pos+4])[0]
                pos += 4
                fields.setdefault(field_num, []).append(('fixed32', val))
            else:
                break
        except Exception:
            break
    return fields

def open_readonly_db(db_path):
    """Opens an SQLite database in safe read-only WAL mode"""
    db_uri = Path(os.path.abspath(db_path)).as_uri()
    uri = f"{db_uri}?mode=ro"
    try:
        con = sqlite3.connect(uri, uri=True, timeout=3.0)
        con.execute("PRAGMA busy_timeout = 2000;")
        con.execute("PRAGMA query_only = ON;")
        return con
    except sqlite3.OperationalError:
        imm_uri = f"{db_uri}?mode=ro&immutable=1"
        return sqlite3.connect(imm_uri, uri=True, timeout=2.0)

def extract_session_title(cur):
    """Extracts official session title or user intent from steps table"""
    try:
        # 1. Step type 23 (Trajectory Description / Title generated by Antigravity)
        for r in cur.execute('SELECT step_payload FROM steps WHERE step_type = 23 ORDER BY idx DESC').fetchall():
            if r[0]:
                b = r[0]
                p = b.find(b'\xf2\x01')
                if p != -1:
                    pos = p + 2
                    while pos < len(b) and (b[pos] & 0x80):
                        pos += 1
                    pos += 1
                    if pos < len(b) and b[pos] == 0x22 and pos + 1 < len(b):
                        length = b[pos+1]
                        title = b[pos+2:pos+2+length].decode('utf-8', errors='ignore')
                        if title and len(title.strip()) >= 2:
                            return title.strip()
        # 2. Fallback: check first user request in step_type 14
        for r in cur.execute('SELECT step_payload FROM steps WHERE step_type = 14 ORDER BY idx ASC LIMIT 2').fetchall():
            if r[0]:
                import re
                txt = r[0].decode('utf-8', errors='ignore')
                m = re.search(r'<USER_REQUEST>\s*([\s\S]*?)\s*</USER_REQUEST>', txt)
                if m:
                    line = m.group(1).strip().splitlines()[0][:32]
                    return line
    except Exception:
        pass
    return ''

def normalize_model_specs(raw):
    raw_lower = (raw or '').lower().strip()
    if 'claude' in raw_lower:
        if 'opus' in raw_lower:
            return {
                'id': 'claude-opus-4-6',
                'name': 'Claude Opus 4.6',
                'context_window': 200000,
                'context_label': '200k'
            }
        return {
            'id': 'claude-sonnet-4-6',
            'name': 'Claude Sonnet 4.6',
            'context_window': 200000,
            'context_label': '200k'
        }
    if 'gpt' in raw_lower:
        return {
            'id': 'gpt-oss-120b',
            'name': 'GPT-OSS 120B',
            'context_window': 131072,
            'context_label': '128k'
        }
    # Default: Gemini models all feature 1M (1,048,576) context windows
    name = 'Gemini 3.8 Flash'
    if '3.7' in raw_lower:
        name = 'Gemini 3.7 Flash'
    elif '3.6' in raw_lower:
        name = 'Gemini 3.6 Flash'
    elif '3.1' in raw_lower or 'pro' in raw_lower:
        name = 'Gemini 3.1 Pro'
    return {
        'id': raw or 'gemini-3.8-flash-high',
        'name': name,
        'context_window': 1048576,
        'context_label': '1M'
    }

def extract_session_model(cur):
    """Detects active model used in the session from executor_metadata or gen_metadata"""
    try:
        import re
        rows = cur.execute('SELECT data FROM executor_metadata ORDER BY idx DESC LIMIT 10').fetchall()
        for r in rows:
            if r[0]:
                txt = r[0].decode('latin-1', errors='ignore')
                found = re.findall(r'(?:gemini-[a-zA-Z0-9\.\-]+|claude-[a-zA-Z0-9\.\-]+|gpt-[a-zA-Z0-9\.\-]+)', txt)
                if found:
                    return normalize_model_specs(found[0])
        rows = cur.execute('SELECT data FROM gen_metadata ORDER BY idx DESC LIMIT 10').fetchall()
        for r in rows:
            if r[0]:
                txt = r[0].decode('latin-1', errors='ignore')
                found = re.findall(r'(?:gemini-[a-zA-Z0-9\.\-]+|claude-[a-zA-Z0-9\.\-]+|gpt-[a-zA-Z0-9\.\-]+)', txt)
                if found:
                    return normalize_model_specs(found[0])
    except Exception:
        pass
    return normalize_model_specs('gemini-3.8-flash-high')

def collect_tokens(target_date=None, target_workspace=""):
    if not target_date:
        target_date = datetime.now().strftime('%Y-%m-%d')
    
    target_workspace_norm = os.path.normpath(target_workspace).lower() if target_workspace else ""

    summary = {
        "today": {
            "date": target_date,
            "total_tokens": 0,
            "input_tokens": 0,
            "cached_tokens": 0,
            "output_tokens": 0,
            "thinking_tokens": 0,
            "cache_hit_rate": 0.0,
            "sessions": 0,
            "turns": 0
        },
        "current_project": {
            "name": os.path.basename(target_workspace.rstrip('/\\')) if target_workspace else "",
            "path": target_workspace,
            "total_tokens": 0,
            "input_tokens": 0,
            "cached_tokens": 0,
            "output_tokens": 0,
            "thinking_tokens": 0,
            "sessions": 0,
            "session_list": [],
            "active_session": None
        },
        "current_session": None,
        "all_time": {
            "total_tokens": 0,
            "sessions": 0
        },
        "projects": defaultdict(lambda: {"total": 0, "input": 0, "cached": 0, "output": 0, "thinking": 0, "sessions": 0}),
        "project_sessions": defaultdict(list),
        "daily_map": defaultdict(lambda: {"total": 0, "input": 0, "cached": 0, "output": 0, "thinking": 0, "turns": 0})
    }

    db_paths = []
    for s_dir in DATA_SOURCES:
        if os.path.isdir(s_dir):
            db_paths.extend(glob.glob(os.path.join(s_dir, "*.db")))

    active_session = None
    for db_path in db_paths:
        if os.path.getsize(db_path) == 0:
            continue
        try:
            convo_id = os.path.splitext(os.path.basename(db_path))[0]
            with closing(open_readonly_db(db_path)) as con:
                cur = con.cursor()

                # 1. Project path from trajectory_metadata_blob
                workspace_path = ""
                project_name = "General"
                try:
                    row = cur.execute('SELECT data FROM trajectory_metadata_blob').fetchone()
                    if row and row[0]:
                        text = row[0].decode('latin-1', errors='ignore')
                        import re
                        m = re.search(r'file:///([^\x00-\x20\x7f-\xff]+)', text)
                        if m:
                            raw_path = urllib.parse.unquote(m.group(1))
                            workspace_path = os.path.normpath(raw_path)
                            folder = os.path.basename(workspace_path.rstrip('/\\'))
                            if folder:
                                project_name = folder
                except Exception:
                    pass

                is_current_workspace = False
                if target_workspace_norm and workspace_path:
                    if target_workspace_norm in workspace_path.lower() or workspace_path.lower() in target_workspace_norm:
                        is_current_workspace = True

                # 2. Step timestamps
                step_times = {}
                try:
                    for r in cur.execute('SELECT idx, metadata FROM steps WHERE metadata IS NOT NULL').fetchall():
                        try:
                            s_proto = parse_proto(r[1])
                            if 1 in s_proto:
                                for _, p in s_proto[1]:
                                    sub_time = parse_proto(p)
                                    if 1 in sub_time and sub_time[1]:
                                        step_times[r[0]] = sub_time[1][0][1]
                        except Exception:
                            pass
                except Exception:
                    pass

                # 3. Token usage from gen_metadata
                session_has_today = False
                session_total_tokens = 0
                session_input = 0
                session_cached = 0
                session_output = 0
                session_thinking = 0
                session_turns = 0
                session_dates = []
                last_turn_context = 0
                last_turn_input = 0
                last_turn_cached = 0

                try:
                    rows = cur.execute('SELECT idx, data FROM gen_metadata ORDER BY idx ASC').fetchall()
                    for idx, data in rows:
                        try:
                            top = parse_proto(data)
                            if 1 not in top:
                                continue
                            for _, p1 in top[1]:
                                sub1 = parse_proto(p1)
                                if 4 not in sub1:
                                    continue
                                for _, p4 in sub1[4]:
                                    usage = parse_proto(p4)
                                    inp = usage.get(2, [(0, 0)])[0][1]
                                    out = usage.get(3, [(0, 0)])[0][1]
                                    cached = usage.get(5, [(0, 0)])[0][1]
                                    thinking = usage.get(10, [(0, 0)])[0][1]
                                    tot = inp + cached + out

                                    last_turn_context = inp + cached
                                    last_turn_input = inp
                                    last_turn_cached = cached

                                    session_total_tokens += tot
                                    session_input += inp
                                    session_cached += cached
                                    session_output += out
                                    session_thinking += thinking
                                    session_turns += 1

                                    summary["all_time"]["total_tokens"] += tot

                                    # Project stats
                                    p_entry = summary["projects"][project_name]
                                    p_entry["total"] += tot
                                    p_entry["input"] += inp
                                    p_entry["cached"] += cached
                                    p_entry["output"] += out
                                    p_entry["thinking"] += thinking

                                    if is_current_workspace:
                                        cp = summary["current_project"]
                                        cp["total_tokens"] += tot
                                        cp["input_tokens"] += inp
                                        cp["cached_tokens"] += cached
                                        cp["output_tokens"] += out
                                        cp["thinking_tokens"] += thinking

                                    # Check timestamp
                                    ts = step_times.get(idx)
                                    if not ts:
                                        ts = int(os.path.getmtime(db_path))
                                    step_date = datetime.fromtimestamp(ts).strftime('%Y-%m-%d')
                                    session_dates.append(step_date)

                                    # Daily map for heatmap
                                    dm = summary["daily_map"][step_date]
                                    dm["total"] += tot
                                    dm["input"] += inp
                                    dm["cached"] += cached
                                    dm["output"] += out
                                    dm["thinking"] += thinking
                                    dm["turns"] += 1

                                    if step_date == target_date:
                                        session_has_today = True
                                        td = summary["today"]
                                        td["total_tokens"] += tot
                                        td["input_tokens"] += inp
                                        td["cached_tokens"] += cached
                                        td["output_tokens"] += out
                                        td["thinking_tokens"] += thinking
                                        td["turns"] += 1
                        except Exception:
                            pass
                except Exception:
                    pass

                if session_total_tokens > 0:
                    summary["all_time"]["sessions"] += 1
                    summary["projects"][project_name]["sessions"] += 1
                    if is_current_workspace:
                        summary["current_project"]["sessions"] += 1

                    db_mtime = int(os.path.getmtime(db_path))
                    s_date = session_dates[-1] if session_dates else datetime.fromtimestamp(db_mtime).strftime('%Y-%m-%d')
                    sess_title = extract_session_title(cur)
                    sess_model = extract_session_model(cur)
                    ctx_pct = round((last_turn_context / sess_model["context_window"]) * 100, 1) if sess_model["context_window"] > 0 else 0.0

                    sess_item = {
                        "id": convo_id[:8],
                        "full_id": convo_id,
                        "title": sess_title,
                        "date": s_date,
                        "model": sess_model["name"],
                        "model_id": sess_model["id"],
                        "context_window": sess_model["context_window"],
                        "context_label": sess_model["context_label"],
                        "context_pct": ctx_pct,
                        "total_tokens": session_total_tokens,
                        "context_tokens": last_turn_context,
                        "input_tokens": session_input,
                        "cached_tokens": session_cached,
                        "output_tokens": session_output,
                        "thinking_tokens": session_thinking,
                        "turns": session_turns,
                        "mtime": db_mtime
                    }
                    summary["project_sessions"][project_name].append(sess_item)
                    if is_current_workspace:
                        summary["current_project"]["session_list"].append(sess_item)
                        if active_session is None or db_mtime > active_session["mtime"]:
                            active_session = sess_item

                if session_has_today:
                    summary["today"]["sessions"] += 1

        except Exception:
            continue

    if active_session:
        summary["current_session"] = active_session
        summary["current_project"]["active_session"] = active_session

    # Calculate cache hit rate
    td = summary["today"]
    prompt_total = td["input_tokens"] + td["cached_tokens"]
    if prompt_total > 0:
        td["cache_hit_rate"] = round((td["cached_tokens"] / prompt_total) * 100, 1)

    # Convert projects dict to list with nested sessions
    proj_list = []
    for k, v in summary["projects"].items():
        if v["total"] > 0:
            sess_list = summary["project_sessions"].get(k, [])
            sess_list.sort(key=lambda s: s["total_tokens"], reverse=True)
            proj_list.append({
                "name": k,
                "total_tokens": v["total"],
                "input_tokens": v["input"],
                "cached_tokens": v["cached"],
                "output_tokens": v["output"],
                "thinking_tokens": v["thinking"],
                "sessions": v["sessions"],
                "session_items": sess_list
            })
    proj_list.sort(key=lambda x: x["total_tokens"], reverse=True)
    summary["projects"] = proj_list

    # Convert daily map to sorted list for Heatmap
    all_daily = []
    for d, val in sorted(summary["daily_map"].items()):
        all_daily.append({
            "date": d,
            "total": val["total"],
            "input": val["input"],
            "cached": val["cached"],
            "output": val["output"],
            "thinking": val["thinking"],
            "turns": val["turns"]
        })
    summary["all_daily"] = all_daily

    # Clean up internal maps
    del summary["project_sessions"]
    del summary["daily_map"]

    return summary

def main():
    import argparse
    if sys.platform == 'win32' and hasattr(sys.stdout, 'reconfigure'):
        try:
            sys.stdout.reconfigure(encoding='utf-8')
        except Exception:
            pass

    parser = argparse.ArgumentParser(description="Antigravity Token Collector")
    parser.add_argument("--date", type=str, default="", help="Date in YYYY-MM-DD format (default: today)")
    parser.add_argument("--workspace", type=str, default="", help="Current workspace directory path")
    args = parser.parse_args()

    result = collect_tokens(target_date=args.date, target_workspace=args.workspace)
    print(json.dumps(result, ensure_ascii=False))

if __name__ == "__main__":
    main()
